## NUMPY

In [3]:
!pip install numpy

     ---------------------------------------- 12.9/12.9 MB 2.5 MB/s eta 0:00:00



[notice] A new release of pip available: 22.3.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

In [6]:
# creating array using numpy
arr1 = np.array([1,2,3,4,5])
print (arr1)


[1 2 3 4 5]


In [8]:
#craeting 2d array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


#### shape method

In [12]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 5)


#### arange method

In [17]:
arr3=np.arange(0,10,2)
k=arr3.reshape(1,5)
print(k)
l=arr3.reshape(5,1)
print(l)

[[0 2 4 6 8]]
[[0]
 [2]
 [4]
 [6]
 [8]]


ones method

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### creating identity matrix

In [20]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Numpy vectorized operation

In [22]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**arr2)
print(arr1%arr2)

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[      1     128    6561  262144 9765625]
[1 2 3 4 5]


#### array slicing and indexing

In [29]:
arr5=np.array([[1,2,3,4,5],[12,23,34,45,56],[54,52,76,13,26]])
print(arr5)


[[ 1  2  3  4  5]
 [12 23 34 45 56]
 [54 52 76 13 26]]


In [30]:
## slicing
print(arr5[1:,1:3])

[[23 34]
 [52 76]]


In [31]:
#indexing
print(arr5[1][3])

45


In [32]:
#modifing array
arr5[0][3]=100
print(arr5)

[[  1   2   3 100   5]
 [ 12  23  34  45  56]
 [ 54  52  76  13  26]]


### Statstical concepts
#### normalization


to have a mean of 0 and standard deviation of 1

In [36]:
data = np.array([1,2,3,4,5])

## calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

## normalize the data
normalized_data = (data-mean)/std_dev
print("normalized data:",normalized_data)

normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
